Update docs to document new optional status of logback dependency
ome/bio-formats-documentation pull request #286
Opened 2023-02-10 14:03 UTC by dgault

This PR is a follow up to the logback dependency work as per the recommendation inhttps://github.com/https://github.com/ome/bioformats/pull/3943#issuecomment-1422963707

It updates the Bio-Formats docs to make it clearer for users that a logging dependency must be explicitly declared.

Re-opened PR on a clean branch, originally https://github.com/ome/bio-formats-documentation/pull/285

2023-02-10 16:53 UTC, melissalinkert approved these changes

2023-02-10 17:38 UTC, sbesson requested changes
A few inline suggestions for typos around the `jackson-*` versions. Otherwise looks good to me

2023-02-10 17:38 UTC, sbesson commented on sphinx/developers/java-library.rst
> +    * - `jackson-annotations v12.14.1 <https://github.com/FasterXML/jackson-annotations>`_
Should this be
```suggestion
    * - `jackson-annotations v2.14.1 <https://github.com/FasterXML/jackson-annotations>`_
```

2023-02-10 17:38 UTC, sbesson commented on sphinx/developers/java-library.rst
> +      - com.fasterxml.jackson.core:jackson-annotations:12.14.1
```suggestion
      - com.fasterxml.jackson.core:jackson-annotations:2.14.1
```

2023-02-10 17:38 UTC, sbesson commented on sphinx/developers/java-library.rst
> +    * - `jackson-databind v12.14.1 <https://github.com/FasterXML/jackson-databind>`_
```suggestion
    * - `jackson-databind v2.14.1 <https://github.com/FasterXML/jackson-databind>`_
```

2023-02-10 17:38 UTC, sbesson commented on sphinx/developers/java-library.rst
> +      - com.fasterxml.jackson.core:jackson-databind:12.14.1
```suggestion
      - com.fasterxml.jackson.core:jackson-databind:2.14.1
```

2023-02-11 13:52 UTC, sbesson approved these changes

2023-02-13 16:34 UTC, sbesson commented on sphinx/developers/java-library.rst
> +As of Bio-Formats 6.12.0 consumers will have to directly declare a dependency for
```suggestion

As of Bio-Formats 6.12.0 consumers will have to directly declare a dependency for 
```

2023-02-14 13:14 UTC, merged