Add documentation for Bioconductor RBioFormats
ome/bio-formats-documentation pull request #295
Opened 2023-04-07 16:34 UTC by dgault

This is a follow up to the request raised on forum thread https://forum.image.sc/t/possible-addition-to-https-www-openmicroscopy-org-bio-formats-downloads-rbioformats/79474

This PR adds 2 new pages, adding Bioconductor to the Users list (under libraries and sciprting applications) and also a page on `Using Bio-Formats in R` under the developer section.

2023-04-25 09:53 UTC, sbesson reviewed
Thanks @dgault, the addition of two separate pages (user & dev) makes sense to me and follows the established pattern for e.g. MATLAB and other applications - see https://bio-formats--295.org.readthedocs.build/en/295/users/index.html and https://bio-formats--295.org.readthedocs.build/en/295/developers/index.html.

My primary question is whether the user page should be called `Bioconductor` under `Libraries and scripting applications` or `R` under `Numerical data processing applications` e.g. by symmetry with MATLAB or Octave.

2023-04-25 09:53 UTC, sbesson commented on sphinx/developers/r-dev.rst
> +    browseVignettes("RBioFormats")
Possibly the dev section could include a reference to https://bioconductor.org/packages/devel/bioc/vignettes/RBioFormats/inst/doc/RBioFormats.html which is the API documentation

2023-04-25 14:22 UTC, dgault commented
I can see either option making sense for the user page, happy to move it to `R` under `Numerical data processing applications` if that is preferred.

2023-04-25 14:40 UTC, melissalinkert commented
Maybe worth adding a statement to the Bioconductor user page similar to what's at the top of the dev page (so it's clearer that this isn't something OME develops). Otherwise looks fine to me, I don't have strong opinions on which section to use for the user page.

2023-04-26 09:17 UTC, sbesson requested changes
One rendering issue. Otherwise looks like good to me

2023-04-26 09:17 UTC, sbesson commented on sphinx/developers/r-dev.rst
> +For further details and examples of how to use the package, please see the `API documentation<https://bioconductor.org/packages/devel/bioc/vignettes/RBioFormats/inst/doc/RBioFormats.html>`_
```suggestion
For further details and examples of how to use the package, please see the `API documentation <https://bioconductor.org/packages/devel/bioc/vignettes/RBioFormats/inst/doc/RBioFormats.html>`_ 
```

Looks like you need an extra space to get this rendered as an hyperlink.

2023-04-26 09:58 UTC, sbesson approved these changes

2023-04-26 14:22 UTC, merged