Add version history for Bio-Formats 7.3.0
ome/bio-formats-documentation pull request #372
Opened 2024-04-17 16:27 UTC by dgault

Adding version history for the release of 7.3.0

For a full list of included PR's see https://github.com/ome/bioformats/milestone/100?closed=1

2024-04-17 16:58 UTC, melissalinkert requested changes
Noted a couple of mismatches between release notes and actual component versions. I suspect those are changes that need to happen in Bio-Formats itself.

2024-04-17 16:58 UTC, melissalinkert commented on sphinx/about/whats-new.rst
> +   - fixed and exception in CellSens 4.1 data by updating the handling of orphaned ets files (thanks to Edward Scanlon)
```suggestion
   - fixed an exception in CellSens 4.1 data by updating the handling of orphaned ets files (thanks to Edward Scanlon)
```

2024-04-17 16:58 UTC, melissalinkert commented on sphinx/about/whats-new.rst
> +* `ome-metakit` was upgraded to 5.3.7
https://github.com/ome/bioformats/pull/4183 bumped ome-metakit to 5.3.6 (but 5.3.7 is latest).

2024-04-17 16:58 UTC, melissalinkert commented on sphinx/about/whats-new.rst
> +* `ome-poi` was upgraded to 5.3.9
https://github.com/ome/bioformats/pull/4183 bumped ome-poi to 5.3.8 (but 5.3.9 is latest).

2024-04-18 09:41 UTC, dgault commented
Good spot @melissalinkert, in this case it is the docs which are correct. I have opened a further PR against bioformats to bump these 2 components to the latest version: https://github.com/ome/bioformats/pull/4185

2024-04-18 10:25 UTC, sbesson approved these changes

2024-04-18 11:43 UTC, merged